/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tasks with search, filter, and pagination */
        get: operations["get_TaskList"];
        put?: never;
        /** Create a new task */
        post: operations["post_TaskCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single task by ID */
        get: operations["get_TaskRead"];
        /** Update a task by ID */
        put: operations["put_TaskUpdate"];
        post?: never;
        /** Delete a task by ID */
        delete: operations["delete_TaskDelete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dummy/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** this endpoint is an example */
        post: operations["example-endpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_TaskList: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
                search?: string;
                completed?: boolean | null;
                order_by?: "id" | "name" | "slug" | "due_date";
                order_dir?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated task list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        result: {
                            id: number;
                            status: number;
                            status_text?: string;
                        }[];
                        result_info: {
                            count: number;
                            page: number;
                            per_page: number;
                            total_count: number;
                        };
                    };
                };
            };
        };
    };
    post_TaskCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    name: string;
                    slug: string;
                    /** @default 0 */
                    status?: number;
                    /** @default  */
                    description?: string;
                    /** @default false */
                    completed?: boolean;
                    due_date: string;
                };
            };
        };
        responses: {
            /** @description Returns the created task */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        result: {
                            id: number;
                            status: number;
                            name: string;
                            status_text?: string;
                        };
                    };
                };
            };
        };
    };
    get_TaskRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        result: {
                            id: number;
                            status: number;
                            name: string;
                            status_text?: string;
                        };
                    };
                };
            };
        };
    };
    put_TaskUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    id: number;
                    name: string;
                    slug: string;
                    /** @default 0 */
                    status?: number;
                    /** @default  */
                    description?: string;
                    /** @default false */
                    completed?: boolean;
                    due_date?: string;
                };
            };
        };
        responses: {
            /** @description Returns the updated task */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        result: {
                            id: number;
                            status: number;
                            name: string;
                            status_text?: string;
                        };
                    };
                };
            };
        };
    };
    delete_TaskDelete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns the deleted task */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        result: {
                            id: number;
                            status: number;
                            name: string;
                            status_text?: string;
                        };
                    };
                };
            };
        };
    };
    "example-endpoint": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description Returns the log details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        result: {
                            msg: string;
                            slug: string;
                            name: string;
                        };
                    };
                };
            };
        };
    };
}
